name: 'SwiftConcur CI'
description: 'Detect and track Swift concurrency warnings in your codebase'
author: 'SwiftConcur'
branding:
  icon: 'check-circle'
  color: 'orange'

inputs:
  swift-version:
    description: 'Swift version to use'
    required: false
    default: 'latest'
  
  workspace-path:
    description: 'Path to .xcworkspace file'
    required: false
  
  project-path:
    description: 'Path to .xcodeproj file (if not using workspace)'
    required: false
  
  scheme:
    description: 'Xcode scheme to build'
    required: true
  
  configuration:
    description: 'Build configuration (Debug/Release)'
    required: false
    default: 'Debug'
  
  threshold:
    description: 'Maximum allowed warnings (fail if exceeded)'
    required: false
    default: '0'
  
  baseline-path:
    description: 'Path to baseline JSON for comparison'
    required: false
  
  post-comment:
    description: 'Post results as PR comment'
    required: false
    default: 'true'
  
  fail-on-warnings:
    description: 'Fail the action if any warnings found'
    required: false
    default: 'true'
  
  context-lines:
    description: 'Lines of code context to include'
    required: false
    default: '3'
  
  github-token:
    description: 'GitHub token for posting comments'
    required: false
    default: ${{ github.token }}

outputs:
  warning-count:
    description: 'Total number of warnings found'
    value: ${{ steps.parse.outputs.warning-count }}
  
  summary-markdown:
    description: 'Markdown summary of warnings'
    value: ${{ steps.parse.outputs.summary-markdown }}
  
  json-report:
    description: 'Path to full JSON report'
    value: ${{ steps.parse.outputs.json-report }}
  
  new-warnings:
    description: 'Number of new warnings vs baseline'
    value: ${{ steps.parse.outputs.new-warnings }}
  
  fixed-warnings:
    description: 'Number of fixed warnings vs baseline'
    value: ${{ steps.parse.outputs.fixed-warnings }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}