name: SwiftConcur CI Example - Basic
on:
  pull_request:
    branches: [ main ]

jobs:
  concurrency-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: swiftconcur/swiftconcur-ci@v1
        with:
          scheme: 'MyApp'
          workspace-path: 'MyApp.xcworkspace'