name: SwiftConcur CI Example - Multi-Scheme
on: [pull_request]

jobs:
  concurrency-matrix:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        scheme: [App, AppTests, AppUITests]
        
    steps:
      - uses: actions/checkout@v4
      
      - uses: swiftconcur/swiftconcur-ci@v1
        with:
          scheme: ${{ matrix.scheme }}
          project-path: 'MyApp.xcodeproj'
          fail-on-warnings: ${{ matrix.scheme == 'App' }}