name = "swiftconcur-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# R2 bucket for storing raw xcresult files
[[r2_buckets]]
binding = "XCRESULT_BUCKET"
bucket_name = "swiftconcur-xcresults"

# KV namespaces
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "rate-limit-kv"
preview_id = "rate-limit-kv-preview"

[[kv_namespaces]]
binding = "API_TOKENS"
id = "api-tokens-kv"
preview_id = "api-tokens-kv-preview"

# Durable Objects
[[durable_objects.bindings]]
name = "REPO_SHARD"
class_name = "RepoShard"

[[migrations]]
tag = "v1"
new_classes = ["RepoShard"]

# Queues for async processing
[[queues.producers]]
binding = "AI_QUEUE"
queue = "ai-processing"

[[queues.consumers]]
queue = "ai-processing"
max_batch_size = 10
max_batch_timeout = 30

# Environment-specific settings
[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Secrets (set via wrangler secret put)
# SUPABASE_URL
# SUPABASE_SERVICE_KEY
# OPENAI_API_KEY
# SLACK_WEBHOOK_URL
# TEAMS_WEBHOOK_URL