name: Test & Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with: { toolchain: stable, profile: minimal, override: true }
      - run: cargo nextest run
      - run: cargo clippy --workspace --all-targets -- -D warnings