name: Test Action
on:
  push:
    paths:
      - 'action.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'scripts/**'
      - '.github/workflows/test-action.yml'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t swiftconcur-action .
      
      - name: Test entrypoint script
        run: |
          docker run --rm \
            -e INPUT_SCHEME="TestScheme" \
            -e INPUT_PROJECT_PATH="Test.xcodeproj" \
            -e GITHUB_OUTPUT=/dev/null \
            swiftconcur-action || echo "Expected failure"
      
      - name: Lint shell scripts
        run: |
          sudo apt-get install -y shellcheck
          
          # Find and lint all shell scripts
          SHELL_SCRIPTS=""
          
          # Check for entrypoint.sh
          if [ -f "entrypoint.sh" ]; then
            SHELL_SCRIPTS="$SHELL_SCRIPTS entrypoint.sh"
          fi
          
          # Check for scripts in scripts directory
          if compgen -G "scripts/*.sh" > /dev/null; then
            SHELL_SCRIPTS="$SHELL_SCRIPTS scripts/*.sh"
          fi
          
          if [ -n "$SHELL_SCRIPTS" ]; then
            echo "Linting shell scripts: $SHELL_SCRIPTS"
            # Exclude style warnings but keep error and warning level checks
            shellcheck -e SC2129,SC2086,SC1091,SC2034,SC2162,SC2206 $SHELL_SCRIPTS
          else
            echo "No shell scripts found to lint"
          fi
      
      - name: Test Node scripts
        run: |
          cd scripts
          npm install
          node -c post-comment.js